require_relative '../script_init'

main_title 'Add SMEs'

log = Telemetry::MongoidLog
log.clear!

Benchmark.bm do |x|
  x.report do

    smes = {}

    # ------------------ Elementary SMES ---------------------------------
    elementary = {}
    elementary[0] = { :content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Director of curriculum and instruction (5+ years)</li>\n    <li>Classroom teacher (20+ years)</li>\n    <li>Adjunct college professor (5+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>General Education (K-8)</li>\n    <li>Supervision and Administration</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Master of Education in Administration, Supervision and Curriculum</li>\n    <li>Bachelor of Arts in Psychology and Education</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Developed a federally recognized campus drug-free campaign</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Facilitated university-level courses</li>\n  </ul>", :full_name => "Suzan G.", :lock => true, :position => 1, :sluggable_field => "suzan-g", :sortable => false, :static => false, :title => "SME" }

    elementary[1] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Campus administrator (15+ years)</li>\n    <li>Classroom teacher (5+ years)</li>\n    <li>College professor (5+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>General Education (1-8)</li>\n    <li> Mid-Management Administration</li>\n    <li>Curriculum and Instruction</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Master of Arts in Sociology</li>\n    <li>Bachelor of Arts Elementary Education</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Texas Reading Initiative Reading Leader</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Evaluator for national Blue Ribbon Schools</li>\n    <li>Coordinator of Teaching and Learning Center at community college</li>\n    <li>Teacher coach at educational service center</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Wrote grant proposals and implemented grants</li>\n    <li>Presented professional development</li>\n    <li>Authored two successful national Blue Ribbon Schools applications</li>\n  </ul>", :full_name => "Cheryl J.", :lock => true, :position => 3, :sluggable_field => "cheryl-j", :sortable => false, :static => false, :title => "SME"}

    elementary[2] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Classroom teacher (10+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>General Education (EC-8)</li>\n    <li>English as a Second Language (EC-8)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Master of Arts in Education</li>\n    <li>Bachelor of Science in Natural Resources Planning and Interpretation</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Campus Teacher of the Year</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Science curriculum coordinator</li>\n    <li>Served on district-wide mathematics curriculum adoption committee</li>\n    <li>Developed district-wide science curriculum</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Piloted new programs on campus</li>\n    <li>Conducted state-wide teacher professional development and trainings</li>\n    <li>Administered grants</li>\n  </ul>", :full_name => "Monica H.", :lock => true, :position => 4, :sluggable_field => "monica-h", :sortable => false, :static => false, :title => "SME" }

    elementary[3] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n    <li>Classroom teacher (10+ years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n    <li>General Education (EC-6)</li>\r\n    <li>English as a Second Language (EC-6)</li>\r\n    <li>Gifted and Talented (EC-6)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n    <li>Bachelor of Science in Applied Learning and Development</li>\r\n  </ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n    <li>Grade-level team leader</li>\r\n    <li>District gifted and talented advisory committee member</li>\r\n    <li>Teacher advancement program mentor teacher</li>\r\n    <li>District science alignment team member</li>\r\n    <li>District English language arts curriculum management team member</li>\r\n    <li>Participant in district-wide textbook adoption committees</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n    <li>Designed standards-based curriculum and instruction</li>\r\n    <li>Correlated assessments to the state standards</li>\r\n    <li>Member of Texas standardized test (i.e., STAAR) item review committee</li>\r\n  </ul>", :full_name => "Krista M.", :lock => true, :position => 5, :sluggable_field => "krista-m", :sortable => false, :static => false, :title => "SME"}

    elementary[4] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Classroom teacher (5+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>General Education (EC-4)</li>\n    <li>English as a Second Language (EC-4)</li>\n    <li>English Language Arts (4-8)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Master of Education in Educational Administration</li>\n    <li>Bachelor of Science in Education</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Achieved exemplary student passing rates in all subject areas each year</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Campus language arts department chair</li>\n    <li>District-wide language arts curriculum writing and planning team member</li>\n    <li>District-wide textbook adoption committee member</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Developed curriculum and assessments</li>\n    <li>Aligned campus curriculum to state standards</li>\n    <li>Facilitated teacher professional development</li>\n  </ul>\n\n", :full_name => "Ashley S.", :lock => true, :position => 6, :sluggable_field => "ashley-s", :sortable => false, :static => false, :title => "SME"}

    elementary[5] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li> Instructional technologist (10+ years)</li>\n    <li>Classroom teacher (15+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>General Education (1-8)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li> Master of Education in Curriculum and Instruction</li>\n    <li>Bachelor of Science in Elementary Education</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Campus Teacher of the Year</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Grade-level team leader</li>\n    <li>District-wide curriculum writing team member</li>\n    <li>District data coach</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Managed district-wide teacher professional development programs</li>\n    <li>Presented at educational conferences</li>\n  </ul>", :full_name => "Donette S.",  :lock => true, :position => 7, :sluggable_field => "donette-s", :sortable => false, :static => false, :title => "SME"}

    elementary[6] = { :content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (6 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Generalist (EC-6)</li>\r\n<li>ESL Supplemental (EC-6)</li>\r\n<li>Gifted and Talented Supplement (EC-6)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Bachelor of Science</li>\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Professional Learning Committee (PLC)  Grade Level Teacher Leader</li>\r\n<li>District Level Math Representative</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> Principal of Excellence Award Recipient</li>\r\n\r\n\r\n  </ul>\r\n", :full_name => "Amy Q.", :lock => true, :position => 8, :sluggable_field => "amy-q", :sortable => false, :static => false, :title => "SME"}

    elementary[7] = { :content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (35 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Elementary (1-8)</li>\r\n<li>Mid-Management (All Level)</li>\r\n<li>Superintendent (All Level)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Bachelor of Science, Educational Curriculum and Instruction</li>\r\n<li>Masters of Art, Educational Administration, Psychological Services</li>\r\n<li>Post Graduate, Superintendent's Certification</li>\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> District Level Campus Principal Supervisor</li>\r\n<li>District Leadership Team Member</li>\r\n<li>District Level GT Advisory Committee Member</li>\r\n<li>District Level Site Based Committee Member</li>\r\n<li>District Level Conflict Management Committee Member</li>\r\n<li>District Level Discipline Management Planning Committee Member</li>\r\n<li>Campus Grade Level Teacher Leader</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> Administrator of the Year Award Recipient</li>\r\n<li>HEB Regional Secondary Principal of the Year Award Recipient</li>\r\n<li>HEB Regional Secondary Principal of the Year Award Recipient</li>\r\n<li>Association of Texas Professional Educators Member</li>\r\n<li>Texas Middle School Association Member</li>\r\n<li>Association for Supervision and Curriculum Development Member</li>\r\n<li>Texas Association of Secondary School Principals Member</li>\r\n  </ul>\r\n", :full_name => "Diana W.", :lock => true, :position => 9, :sluggable_field => "diana-w", :sortable => false, :static => false, :title => "SME"}

    elementary[8] = { :content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (25+ years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Elementary Self Contained (1-6)</li>\r\n<li>English as a Second Language Endorsement (1-6)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Bachelors of Art in Elementary Education</li>\r\n\r\n</ul>\r\n\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Campus Mentoring  Teacher</li>\r\n<li>Campus Level Teacher Team Leader</li>\r\n<li>District Level Curriculum Writer</li>\r\n<li>Campus Level Faculty Advisory Board Member</li>\r\n  </ul>\r\n", :full_name => "Lori F.", :lock => true, :position => 9, :sluggable_field => "lori-f", :sortable => false, :static => false, :title => "SME"}

    elementary[9] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (8 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Early Childhood Education (P-5)</li>\r\n<li>Technology Endorsement</li>\r\n<li>ESOL Certification </li>\r\n<li>Mathematics Endorsement</li>\r\n<li>Gifted Certification</li>\r\n<li>Elementary Education</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Master's Degree Early Childhood Education</li>\r\n<li>Bachelor's Degree Early Childhood Education, summa cum laude</li>\r\n\r\n</ul>\r\n\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Campus Level Multi-Criteria Team Leader</li>\r\n<li>Campus Level Professional Development Team Leader</li>\r\n<li>Campus Level Teacher Mentor</li>\r\n<li>Campus Level Leadership Team Member</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> Teacher of the Year</li>\r\n<li>Committee Member for Curriculum Development</li>\r\n  </ul>\r\n", :full_name => "Megan V.", :lock => true, :position => 10, :sluggable_field => "megan-v", :sortable => false, :static => false, :title => "SME"}

    elementary[10] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (29 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Elementary Self-Contained  (1-8)</li>\r\n<li>Elementary Art ( 1-8)</li>\r\n<li>English as a Second Language Supplemental (1-8)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Bachelor of Science</li>\r\n</ul>\r\n\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> District Science Vertical Alignment Committee Member</li>\r\n<li>Campus Math Vertical Alignment Committee Member</li>\r\n<li>Campus Leadership Team Member</li>\r\n<li>District Leadership Team Member</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> Member of District Curriculum Writing Team for elementary science, writing and math</li>\r\n<li>ESL Certified</li>\r\n<li>Named Campus Level Teacher of the Year</li>\r\n<li>Campus Mentor for teachers</li>\r\n  </ul>\r\n", :full_name => "Melissa S.", :lock => true, :position => 11, :sluggable_field => "melissa-s", :sortable => false, :static => false, :title => "SME"}

    elementary[11] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (14 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li>Elementary Education (Grades 1 - 8)</li>\r\n<li>Elementary Mathematics (Grades 1-8)</li>\r\n<li>Early Childhood (PK - K)</li>\r\n<li> English as a Second Language(PK - 8)</li>\r\n<li>Master Reading Teacher</li>\r\n\r\n</ul>\r\n\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Bachelor of Science in Education</li>\r\n<li>Master of Education in Elementary Education</li>\r\n\r\n</ul>\r\n\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Preschool Director</li>\r\n<li> Elementary Math Lead Teacher</li>\r\n<li> Campus Level Team Leader</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li>Campus Leadership Team Representative</li>\r\n<li> Math Textbook Adoption Committee Representative</li>\r\n\r\n  </ul>\r\n", :full_name => "Kelly M.", :lock => true, :position => 12, :sluggable_field => "kelly-m", :sortable => false, :static => false, :title => "SME"}

    elementary[12] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (14 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li>Elementary Self-Contained (1-6)</li>\r\n<li>Principal (All Level)</li>\r\n\r\n</ul>\r\n\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Bachelor of Science in Child Development & Family Relationships</li>\r\n<li> Master of Education in Education Leadership</li>\r\n</ul>\r\n\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li>Campus Level Math Committee Chairperson\r\n<li>Campus Leadership Team Member</li>\r\n<li> Campus Level Site Based Decision Making Committee Member</li>\r\n<li> Campus Level RtI Committee Member</li>\r\n  </ul>\r\n", :full_name => "Salina A.", :lock => true, :position => 13, :sluggable_field => "salina-a", :sortable => false, :static => false,  :title => "SME"}

    smes["elementary"] = elementary


    # ------------------ ELAR SMES ---------------------------------

    elar = {}
    elar[0] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Classroom teacher (20+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>English Language Arts (6-12)</li>\n    <li>English as a Second Language (6-12)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Bachelor of Arts in English</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Association of Texas Professional Educators (ATPE) State Committee Chair and Local President</li>\n    <li>District-wide curriculum writing committee member</li>\n    <li>University Interscholastic League (UIL) coach</li>\n    <li>Reading program coordinator</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Designed standard-based curriculum and instruction</li>\n    <li>Mentored teachers</li>\n    <li>Provided training in Advanced Placement and gifted and talented instructional strategies</li>\n  </ul>\n", :full_name => "Kathy P.", :lock => true, :position => 1, :sluggable_field => "kathy-p", :sortable => false, :static => false, :title => "SME"}

    elar[1] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Classroom teacher (5+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>General Education (EC-4)</li>\n    <li>English as a Second Language (ESL) (K-12)</li>\n    <li>Special Education (K-12)</li>\n    <li>English Language Arts (9-12)</li>\n    <li>Physical Education (K-12)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Bachelor of Science in Education (Magna Cum Laude)</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Teacher of the Month</li>\n    <li>Master reading teacher</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Campus team leader</li>\n    <li>Trainer in meeting the needs of special education students</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Created curricula for ESL and bilingual students</li>\n    <li>Developed individualized education plans (IEPs) for special education students</li>\n    <li>Created classroom management systems for special education classes</li>\n  </ul>\n", :full_name => "Danielle H.", :lock => true, :position => 2, :sluggable_field => "danielle-h", :sortable => false, :static => false, :title => "SME"}

    elar[2] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Classroom teacher (5+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>English Language Arts (9-12)</li>\n    <li>Advanced Placement (AP) (9-12)</li>\n    <li>Gifted and Talented (9-12)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Master of Arts in English</li>\n    <li>Bachelor of Arts in Telecommunications</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Texas Virtual School Network (TxVSN) instructor and course evaluator</li>\n    <li>Instructional television (ITV) instructor</li>\n  </ul>\n", :full_name => "Patti T.", :lock => true, :position => 3, :sluggable_field => "patti-t", :sortable => false, :static => false, :title => "SME"}

    smes["elar"] = elar

    # ------------------ Math SMES ---------------------------------

    math = {}

    math[0] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Classroom teacher (20+ years)</li>\n    <li>Public school administrator (5+ years)</li>\n    <li>Mathematics intervention specialist (5+ years)</li>\n    <li>University professor (5+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>Mathematics (4-8)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Ph.D. in Reading</li>\n    <li>Master of Science in Psychology</li>\n    <li>Bachelor of Arts in Psychology and Political Science</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Campus Teacher of the Year</li>\n    <li>Deaver Foundation Award for Excellence in Teaching</li>\n    <li>Outstanding Young Educator Award</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Research associate </li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Conducted extensive research in second-language teaching strategies</li>\n    <li>Authored books and articles on teaching best practices</li>\n    <li>Delivered presentations at educational conferences</li>\n  </ul>", :full_name => "Peggy C.", :lock => true, :position => 1, :sluggable_field => "peggy-c", :sortable => false, :static => false, :title => "SME"}

    math[1] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Instructional technologist (20+ years)</li>\n    <li>Classroom teacher (10+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>Superintendent</li>\n    <li>Mathematics (9-12)</li>\n    <li>History (9-12)</li>\n    <li>Computer Information Systems and Computer Literacy</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>E.D. in Educational Administration</li>\n    <li>Master of Arts in Secondary Education</li>\n    <li>Bachelor of Arts in Secondary Education</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Investment Capital Grant Recipient</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Member of alignment team for state-wide online professional development curriculum</li>\n    <li>Texas Computer Education Association (TCEA) charter member</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Aligned curriculum to state standards</li>\n    <li>Developed and implemented virtual school in district</li>\n    <li>Designed and conducted teacher professional development</li>\n  </ul>", :full_name => "Linda S.", :lock => true, :position => 2, :sluggable_field => "linda-s", :sortable => false, :static => false, :title => "SME"}

    math[2] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Classroom teacher (25+ years)</li>\n    <li>Mathematics instructional coach</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>General Education (K-8)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Master of Education in Middle School Mathematics</li>\n    <li>Bachelor of Science in Elementary Education</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>District Teacher of the Year, 2012</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Mathematics curriculum leader</li>\n    <li>District strategic planning committee member</li>\n    <li>Textbook adoption and curriculum planning committee member</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Facilitated textbook selection</li>\n    <li>Provided professional development in mathematics best practices</li>\n    <li>Developed curriculum and assessment</li>", :full_name => "Kathy B.", :lock => true, :position => 3, :sluggable_field => "kathy-b", :sortable => false, :static => false, :title => "SME"}

    math[3] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li> Instructional technologist (10+ years)</li>\n    <li>Classroom teacher (15+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>General Education (1-8)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li> Master of Education in Curriculum and Instruction</li>\n    <li>Bachelor of Science in Elementary Education</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Campus Teacher of the Year</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Grade-level team leader</li>\n    <li>District-wide curriculum writing team member</li>\n    <li>District data coach</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Managed district-wide teacher professional development programs</li>\n    <li>Presented at educational conferences</li>\n  </ul>", :full_name => "Donette S.", :lock => true, :position => 4, :sluggable_field => "donette-s", :sortable => false, :static => false, :title => "SME"}

    math[4] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>District and campus administrator (10+ years)</li>\n    <li>Classroom teacher (10+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>Superintendent</li>\n    <li>Principal (PK-12)</li>\n    <li>Mathematics (6-12)</li>\n    <li>Spanish (6-12)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Ph.D. in Educational Leadership with emphasis on Curriculum and Instruction (estimated graduation \n2014)</li>\n    <li>Master of Arts in Educational Administration</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Campus Teacher of Year</li>\n    <li>Recipient: Educator Excellence Academy Fellowship</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Texas Principal Excellence Program</li>\n    <li>Supervised district-wide curriculum adoption</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Led professional training</li>\n    <li>Published books on college readiness and the implementation of the Common Core State Standards</li>\n    <li>Conducted curriculum audits</li>\n  </ul>", :full_name => "Ben J.", :lock => true, :position => 5, :sluggable_field => "ben-j", :sortable => false, :static => false, :title => "SME"}

    math[5] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Classroom teacher (10+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>Mathematics (6-12)</li>\n    <li>Physics (8 -12)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Bachelor of Science in Mathematics</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Campus and district-wide mathematics department chair</li>\n    <li>Campus and district-wide Texas-STEM coordinator</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Reviewed online curriculum for alignment to state and national standards</li>\n    <li>Presented at state educational conferences</li>\n    <li>Science camp director</li>\n  </ul>", :full_name => "Kyle C.", :lock => true, :position => 6, :sluggable_field => "kyle-c", :sortable => false, :static => false, :title => "SME"}

    math[6] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Middle School Math Coach, Instructional Specialist (8 years)</li>\n    <li> Classroom teacher (15 years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>General Education (1-8)</li>\n    <li>Secondary Mathematics (6-12)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Master in Education in Curriculum/Instructions with Mathematics Education</li>\n    <li>Bachelor of Science in Education, Minor in Mathematics</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Modeled instruction and assisted 14 secondary math teachers</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Conducted classroom observations for content instruction</li>\n    <li>Developed and facilitated professional development trainings</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Developed secondary math benchmark assessments</li>\n    <li>Coordinated data-driven intervention plans for Saturday school, extended day, and TAKS camp</li>\n    <li>Implemented math inclusion program</li>\n  </ul>", :full_name => "Jaye S.", :lock => true, :position => 7, :sluggable_field => "jaye-s",  :sortable => false, :static => false, :title => "SME"}

    math[7] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (23 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Secondary Mathematics (6-12)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Bachelor of Arts in Mathematics</li>\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Texas Regional Collaborative Math Mentor Teacher</li>\r\n<li>Supervising Teacher of Student Teachers</li>\r\n<li>Association of Texas Professional Educators Local Unit Treasurer</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> NASA Middle School Aerospace Scholar</li>\r\n<li>Association of Texas Professional Educators Member</li>\r\n  </ul>\r\n", :full_name => "Angie G.", :lock => true, :position => 7, :sluggable_field => "angie-g", :sortable => false, :static => false, :title => "SME"}

    math[8] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (8 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Mathematics (4-12)</li>\r\n<li>Science ( 8-12)</li>\r\n<li>Family and Consumer Science Generalist (4-8)</li>\r\n<li>English as a Second Language Supplemental (1-12)</li>\r\n<li>Special Education Supplemental (4-12)</li>\r\n<li>Gifted and Talented Supplemental (4-12)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Associate of Arts in Economics</li>\r\n<li>Bachelor of Science in Mathematics</li>\r\n<li>Masters in Mathematics Education</li>\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Council of Teachers of Mathematics Treasurer Elect</li>\r\n<li>American Mensa Member </li>\r\n<li>United States Department of Education Small Learning Community Grant Review Panel</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> Johnson Space Center / NASA High School Aerospace Scholars Teacher </li>\r\n  </ul>\r\n", :full_name => "Ellen L.", :lock => true, :position => 8, :sluggable_field => "ellen-l", :sortable => false, :static => false, :title => "SME"}

    math[9] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (13 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Generalist (4-8)</li>\r\n<li>Math (4-8)</li>\r\n<li>English as a Second Language Endorsement Supplement (4-8)</li>\r\n<li>Gifted and Talented Specialist Certification (EC-12)</li>\r\n<li>Special Education( EC-12)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Bachelors of Business Administration</li>\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Campus Level Math Department Chair</li>\r\n<li>Campus Level Science Department Chair</li>\r\n<li>Campus Level Mentor Teacher</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> National Council of Teachers of Mathematics Member</li>\r\n<li>Delta Delta Society of Women Educators Member</li>\r\n  </ul>\r\n", :full_name => "Janet H.", :lock => true, :position => 9, :sluggable_field => "janet-h", :sortable => false, :static => false, :title => "SME"}

    math[10] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (12 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Generalist (4-8)</li>\r\n<li>Mathematics (4-8)</li>\r\n<li>Mathematics (8-12)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Bachelor of Science in Civil Engineering with High Honors</li>\r\n\r\n</ul>\r\n\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> District Level Lesson Plan Task Force Member</li>\r\n<li>Campus Level Academic Team Leader</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> Campus Level Educator of the Year</li>\r\n  </ul>\r\n", :full_name => "Michael V.", :lock => true, :position => 10, :sluggable_field => "michael-v", :sortable => false, :static => false, :title => "SME"}

    math[11] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (16 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Math (6-12)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Masters of Business Administration </li>\r\n<li>Bachelor of Science</li>\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Summer Program Coordinator</li>\r\n  </ul>\r\n", :full_name => "Sue S.",  :lock => true, :position => 11, :sluggable_field => "sue-s",  :sortable => false,  :static => false, :title => "SME"}

    smes["math"] = math

    # ------------------ Science SMES ---------------------------------

    science = {}

    science[0] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Instructional Support Teacher (3 years)</li>\n    <li>Biology, Chemistry, and IPC teacher (10+ years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>Principal (EC-12)</li>\n    <li>Science (8-12)</li>\n    <li>Biology (6-12)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Master of Education in Educational Administration</li>\n    <li>Bachelor of Science</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Developed district sixth grade science curriculum and diagnostic benchmarks</li>\n    <li>Presented professional development in science, vertical alignment, and data analysis</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Provided campus based support for teachers (observation with feedback, model teaching)</li>\n    <li>Participated in the Regional Fuel Cell and Academic Science Bowl and Texas A &amp M Geological Sciences G-Camp</li>\n    <li>Presented at the New Teacher Academy</li>\n    <li>Member of District Curriculum Writing Team for science</li>\n  </ul>", :full_name => "Kelly M.", :lock => true, :position => 1, :sluggable_field => "kelly-m", :sortable => false, :static => false, :title => "SME"}

    science[1]= {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Instructional Coach/Master (2 years)</li>\n    <li>Classroom Teacher (5 years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>Science (4-8)</li>\n    <li>Principal (all levels)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Master of Education in Educational Leadership and Policies</li>\n    <li>Bachelor of Science in Nutrition</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Science department chair; grade level team leader</li>\n    <li>TAP Mentor Teacher</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Science Specialist for campus (provides professional development, models effective teaching)</li>\n    <li>Assists teachers in curriculum alignment</li>\n    <li>Conducts teacher observations and provides feedback</li>\n  </ul>", :full_name => "Crystal S.", :lock => true, :position => 3, :sluggable_field => "crystal-s", :sortable => false, :static => false, :title => "SME"}

    science[2] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Classroom Science teacher (30 years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>Secondary Biology (6-12)</li>\n    <li>Secondary English (6-12)</li>\n    <li>Secondary Life-Earth (6-12)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Master of Education in Science</li>\n    <li>Bachelor of Education</li>\n  </ul>\n<strong>Distinctions:</strong>\n  <ul>\n    <li>Teacher of the Year for the Science Teacher Association of Texas</li>\n    <li>Texas Regional Collaborative Teaching Excellence Award</li>\n    <li>Gentry Lynn Excellence Award from Texas Tech University</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Past President of Science Teacher Association of Texas</li>\n    <li>Past President of Science Teachers Association, Region 17</li>\n    <li>National Science Teacher Association National Convention Presenter</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>NSTA Texas Tech Advisory Board</li>\n    <li>Led numerous workshops for teachers</li>\n  </ul>", :full_name => "Ross Ann H.", :lock => true, :position => 4, :sluggable_field => "ross-ann-h", :sortable => false, :static => false, :title => "SME"}

    science[3] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (9 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Physical Science (8-12)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Bachelor of Science in Electrical and Electronics Engineering</li>\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Campus based Mentor Teacher</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> Named District Teacher of the Year</li>\r\n\r\n<li>Kinzie Award Winner</li>\r\n\r\n<li>Selected by Top 10% Senior Graduation Class as the Most Inspirational and Influential Educator for 7 Consecutive Years</li>\r\n\r\n  </ul>\r\n", :full_name => "Duane W.", :lock => true, :position => 4, :sluggable_field => "duane-w", :sortable => false, :static => false, :title => "SME"}

    science[4] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (7 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Life Science (8-12)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Masters of Education Curriculum and Instruction</li>\r\n<li>Bachelor of Science</li>\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Campus Mentoring Advisor Teacher</li>\r\n<li>District Level Science Curriculum Writer</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> Campus Level First Year Educator of the Year Award</li>\r\n<li>National Science Teachers Association Member</li>\r\n<li>Texas Association of Biology Teachers Member</li>\r\n<li>Science Teachers Association of Texas Member</li>\r\n<li>American Association for the Advancement of Science Member</li>\r\n  </ul>\r\n", :full_name => "Kyle S.", :lock => true, :position => 4, :sluggable_field => "kyle-s", :sortable => false, :static => false, :title => "SME"}

    smes["science"] = science

    # ------------------ Social Studies SMES ---------------------------------

    social_studies = {}

    social_studies[0] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator ( 9+ years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Mid-Management Administrator (PK-12)</li>\r\n<li>Social Studies  (8-12)</li>\r\n<li>Gifted and Talented (8-12)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Master of Educational Administration</li>\r\n<li>Bachelor of Arts, History</li>\r\n  </ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> District Level Social Studies Coordinator</li>\r\n<li>District Level Gifted and Talented Coordinator </li>\r\n<li>Campus Level Department Chair</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> Texas Association for the Gifted and Talented Rising Star Award</li>\r\n  </ul>\r\n", :full_name => "Amy M.", :lock => true, :position => 1, :sluggable_field => "amy-m", :sortable => false, :static => false, :title => "SME"}

    social_studies[1] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator ( 5 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Principal (PK-12)</li>\r\n<li>Generalist (4-8)</li>\r\n<li>Agriculture Science and Technology (6-12)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Master of Educational Administration</li>\r\n<li>Bachelor of Science, Agriculture Science </li>\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Campus Improvement Team Member</li>\r\n  </ul>\r\n", :full_name => "Kayla W.", :lock => true, :position => 1, :sluggable_field => "kayla-w", :sortable => false, :static => false, :title => "SME"}

    social_studies[2] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator ( 23+ years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li>Principal (PK-12)</li>\r\n<li>Secondary History (6-12)</li>\r\n<li>Secondary Geography (6-12)</li>\r\n<li>Secondary Physical Education (6-12)</li>\r\n<li>Secondary Social Studies Composite (6-12)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li>Master of Educational Administration</li>\r\n<li>Bachelor of Science, History</li>\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> District Level Instructional Coach</li>\r\n<li>Campus Level Site Based Decision Making Committee  Member</li>\r\n<li>Campus Level Discipline Committee Member</li>\r\n<li>Campus Level Attendance Committee Member</li>\r\n<li>Campus level Department Chair</li>\r\n  </ul>\r\n", :full_name => "Raymond C.", :lock => true, :position => 2, :sluggable_field => "raymond-c", :sortable => false, :static => false, :title => "SME"}

    social_studies[3] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator ( 21 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Superintendent (EC-12)</li>\r\n<li>Principal (EC-12)</li>\r\n<li>Secondary History (6-12)</li>\r\n<li>Secondary English(6-12)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Master of Educational Administration</li>\r\n<li>Bachelor of Science, History</li>\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Texas Social Studies Supervisors Association, Past President</li>\r\n<li>Phi Alpha Theta, History Honor Society, Past President</li>\r\n<li>Metroplex Social Studies Supervisors Association, Treasurer</li>\r\n<li>District Level K-12 Coordinator for Social Studies</li>\r\n<li>District Level Strategic Planning Committee Member</li>\r\n<li>District Level Education Improvement Committee Member</li>\r\n<li>District Level Gifted and Talented Committee Member</li>\r\n<li>District Level Vertical Planning Committee Member</li>\r\n<li>Campus Level Assistant Principal</li>\r\n<li>Campus Level Department Chair</li>\r\n<li>Campus Level Team Leader</li>\r\n<li>Campus Level TAKS Coordinator</li>\r\n<li>Campus Level Gifted and Talented Leader</li>\r\n<li>Campus Level Site Based Decision Making Committee Member</li>\r\n</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> District Level Teacher of the Year Award</li>\r\n<li>Delta Kappa Gamma Member</li>\r\n\r\n  </ul>\r\n", :full_name => "Teresa F.", :lock => true, :position => 3, :sluggable_field => "teresa-f", :sortable => false, :static => false, :title => "SME"}

    smes["social_studies"] = social_studies

    # ------------------ Spanish SMES ---------------------------------

    spanish = {}

    spanish[0] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (5 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Bilingual Generalist Spanish (Grades EC-4)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Bachelors of Science in Interdisciplinary Studies</li>\r\n\r\n\r\n</ul>\r\n\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> Campus Level Teacher Team Leader</li>\r\n<li>Campus Level Leadership Committee</li>\r\n<li>Campus Level Curriculum Writing Team Member</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> District Level Celebration of Excellence Award</li>\r\n<li>Aspiring Ed-Leaders Program</li>\r\n  </ul>\r\n", :full_name => "Megan D.", :lock => true, :position => 0, :sluggable_field => "megan-f", :sortable => false, :static => false, :title => "SME"}

    spanish[1] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (17 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li>General Education (1-8)</li>\r\n<li>Bilingual (1-8)</li>\r\n<li>ESL Endorsement (1-8)</li>\r\n<li> Spanish (1-8)</li>\r\n\r\n</ul>\r\n\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li>Masters of Education in Educational Technology Leadership</li>\r\n<li>Bachelors of Science in Applied Learning and Development</li>\r\n</ul>\r\n\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li>District Level Balanced Literacy Trainer</li>\r\n <li> Campus Level Bilingual Instructional Coach</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li>State Board of Education/TEA Textbook Review Panel Member</li>\r\n<li>State Board of Education/TEA TEKS Review Committee</li>\r\n<li>Project Based Learning Facilitator</li>\r\n<li>Multicultural Committee Member</li>\r\n<li>District Curriculum Writer</li>\r\n\r\n  </ul>\r\n", :full_name => "Raquel C.", :lock => true, :position => 1, :sluggable_field => "raquel-c", :sortable => false, :static => false, :title => "SME"}

    spanish[2] = {:content => "<strong>Professional Experience as an Educator:</strong>\r\n  <ul>\r\n<li> Educator (10 years)</li>\r\n  </ul>\r\n<strong>Certifications:</strong>\r\n  <ul>\r\n<li> Principal (Grades EC- 12)</li>\r\n<li>Generalist Grades (4-8)</li>\r\n<li>Generalist Grades (EC-4)</li>\r\n<li>Bilingual Education Supplemental- Spanish Grades (EC-4)</li>\r\n<li>Bilingual Education Supplemental- Spanish Grades (4-8)</li>\r\n  </ul>\r\n<strong>Degrees:</strong>\r\n  <ul>\r\n<li> Masters of Business Administration </li>\r\n<li> Bachelor of Science with a Major in Interdisciplinary Studies </li>\r\n<li>Master Degree in Spanish Language and Culture</li>\r\n<li> Master of Education in Administration</li>\r\n\r\n</ul>\r\n<strong>Leadership:</strong>\r\n  <ul>\r\n<li> State Textbook Review Panel Committee Member</li>\r\n<li>District Level Bilingual Teacher Leader</li>\r\n<li>District Level Lead Elementary Trainer</li>\r\n<li> District Level Science Vertical Team Leader</li>\r\n<li> Campus Improvement Plan Leadership Team</li>\r\n\r\n<li> Student Teacher Mentor</li>\r\n  </ul>\r\n<strong>Other Relevant Experience:</strong>\r\n  <ul>\r\n<li> H-E-B Excellence in Education Statewide Teacher Finalist: Rising Star/Elementary</li>\r\n  </ul>\r\n", :full_name => "Zoila C.", :lock => true, :position => 2, :sluggable_field => "zoila-c", :sortable => false, :static => false, :title => "SME"}

    smes["spanish"] = spanish

    # ------------------ Tech Apps SMES ---------------------------------

    tech_apps = {}
    tech_apps[0] = {:content => "<strong>Professional Experience as an Educator:</strong>\n  <ul>\n    <li>Classroom teacher (Geography, Computer Science, Business - 3 years)</li>\n    <li>Technology Specialist (10 years)</li>\n  </ul>\n<strong>Certifications:</strong>\n  <ul>\n    <li>Secondary Social Studies composite (6-12)</li>\n    <li>Business Education (6-12)</li>\n    <li>Technology Applications (8-12)</li>\n  </ul>\n<strong>Degrees:</strong>\n  <ul>\n    <li>Master of Education in Technology and Cognition</li>\n    <li>Bachelor of Science in Curriculum and Instruction</li>\n  </ul>\n<strong>Leadership:</strong>\n  <ul>\n    <li>Campus technology specialist</li>\n  </ul>\n<strong>Other Relevant Experience:</strong>\n  <ul>\n    <li>Provided professional development for all campus staff</li>\n    <li>Developed curriculum in education department of local newspaper</li>\n  </ul>", :full_name => "Beverly D.", :lock => true, :position => 1, :sluggable_field => "beverly-d", :sortable => false, :static => false, :title => "SME"}

    smes["tech_apps"] = tech_apps

    # ------------------ Methods ---------------------------------

    def delete_children(parent)
      puts "\n---------------------------------\n\n"
      puts "Getting #{parent.title} subtree..."
      children = parent.subtree.to_a

      puts "Records: " + children.count.to_s

      puts "\n---------------------------------\n\n"
      puts "Deleting..."
      children.each_with_index do |child, i|
        unless i == 0
          child.delete
        end
      end

      puts "\n---------------------------------\n\n"
      puts "Deleted #{parent.title} SMEs."
      puts "\n---------------------------------\n\n"
    end

    def create_child(parent, child)
      puts "\n---------------------------------\n\n"
      puts "Creating new #{parent.title} SME..."
      puts "\n---------------------------------\n\n"
      child = Page.create!(parent: parent, title: child[:title], full_name: child[:full_name], sluggable_field: child[:sluggable_field], content: child[:content], lock: child[:lock], sortable: child[:sortable], static: child[:static], position: child[:position])
      puts child.inspect
      puts "\n---------------------------------\n\n"
      puts "#{child.full_name} is created."
      puts "\n---------------------------------\n\n"
    end

    def create_children(parent, children)
      children.each do |k, sme|
        create_child(parent, sme)
      end
    end

    def get_parent(slug)
      puts "Getting parent node #{slug}..."
      Page.where(sluggable_field: slug).first
    end


    # ------------------ Initialize ---------------------------------

    parent_slugs = ['elementary', 'elar', 'math', 'science', 'social_studies', 'spanish', 'tech_apps']

    parent_slugs.each do |slug|
      parent = get_parent(slug)
      delete_children(parent)
      create_children(parent, smes[slug])
    end
  end
end